apiVersion: v1
kind: Service
metadata:
  name: {{ include "acme-wp.fullname" . }}-frontend
  labels:
    {{- include "acme-wp.labels" . | nindent 4 }}
    component: frontend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.frontendPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "acme-wp.selectorLabels" . | nindent 4 }}
    component: frontend
