apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: acme-wp-data
  namespace: acme-wp
  labels:
    app: acme-wp
    component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
