apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: acme-wp-api
  namespace: acme-wp
  labels:
    app: acme-wp
    component: api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
