apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: acme-wp-frontend
  namespace: acme-wp
  labels:
    app: acme-wp
    component: frontend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
